# Generated by Django 5.2.14 on 2026-09-02 21:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='O telefone deve seguir o formato +5588999999999.', regex='^\\+\\d{12,15}$')])),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('closed', 'Encerrada')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-last_message_at',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('role', models.CharField(choices=[('customer', 'Cliente'), ('assistant', 'Assistente')], max_length=16)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation')),
            ],
            options={
                'ordering': ('timestamp', 'id'),
                'indexes': [models.Index(fields=['conversation', 'timestamp'], name='conversatio_convers_70c0ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='conversations.conversation')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='properties.property')),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'constraints': [models.UniqueConstraint(fields=('conversation', 'property'), name='unique_recommendation_per_conversation')],
            },
        ),
    ]
