# Generated by Django 5.2.14 on 2026-09-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('transaction_type', models.CharField(choices=[('aluguel', 'Aluguel'), ('venda', 'Venda')], max_length=16)),
                ('neighborhood', models.CharField(max_length=120)),
                ('neighborhood_key', models.CharField(db_index=True, editable=False, max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bedrooms', models.PositiveSmallIntegerField()),
                ('address', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ('price', 'code'),
                'indexes': [models.Index(fields=['transaction_type', 'neighborhood_key', 'price'], name='properties__transac_213a8f_idx')],
            },
        ),
    ]
